all:
	make quicksort mergesort heapsort

quicksort:
	gcc -std=c99 quicksort.c -o quicksort

mergesort:
	gcc -std=c99 mergesort.c -o mergesort

heapsort:
	gcc -std=c99 heapsort.c -o heapsort

clean: 
	rm quicksort mergesort heapsort
